/* Database schema to keep the structure of entire database. */

CREATE TABLE animals (
    id INTEGER,
    name varchar(100),
    date_of_birth DATE NOT NULL,
    escape_attempts INTEGER,
    neutered BOOLEAN,
    weight_kg DECIMAL

);

ALTER TABLE animals ADD COLUMN species TEXT;

CREATE TABLE owners (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    full_name VARCHAR(100),
    age INTEGER
);

CREATE TABLE species (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    name VARCHAR(75)
);

BEGIN;
ALTER TABLE animals DROP COLUMN species;

ALTER TABLE animals ADD COLUMN species_id INTEGER;

ALTER TABLE animals
ADD FOREIGN KEY (species_id) REFERENCES species (id);

ALTER TABLE animals
ADD COLUMN owner_id INTEGER;

ALTER TABLE animals
ADD FOREIGN KEY (owner_id) REFERENCES owners (id);
COMMIT;
